#!/bin/bash
mkdir -p /tmp/aur/
sudo rm -rf /var/lib/pacman/sync/dawidsoft.db
yaourt -Sb --export /tmp/aur/ google-chrome chromium-widevine virtualbox-ext-oracle --noconfirm
rm -rf ~/github/linux/arch-linux/package/x86_64/virtualbox-ext-oracle*
rm -rf ~/github/linux/arch-linux/package/x86_64/google-chrome*
rm -rf ~/github/linux/arch-linux/package/x86_64/chrome-remote-desktop*
rm -rf ~/github/linux/arch-linux/package/x86_64/chromium-widevine*
cp -r /tmp/aur/*.pkg.tar.xz ~/github/linux/arch-linux/package/x86_64/
rm -rf /tmp/aur/
cd ~/github/linux/arch-linux/package/x86_64/
rm -rf dawidsoft*
repo-add dawidsoft.db.tar.gz *.pkg.tar.xz
rm -rf dawidsoft.db dawidsoft.files
cp dawidsoft.db.tar.gz dawidsoft.db
cp dawidsoft.files.tar.gz dawidsoft.files
cd ~/github/linux/
git add *
git commit -m "first commit"
git push -u origin master
cd ~/
sudo pacman -Syy --noconfirm