#!/bin/bash

umount -l /mnt
mkfs.fat /dev/sda1
mkfs.btrfs -f /dev/sda2
#mkfs.btrfs -f /dev/sda3
mount -o ssd,noatime,nodiratime /dev/sda2 /mnt
mkdir -p /mnt/boot
mkdir -p /mnt/home
#mount -o ssd,noatime,nodiratime /dev/sdb /mnt/home/hp/ssd
mkdir -p /mnt/boot/efi
mount /dev/sda1 /mnt/boot/efi
mount -o ssd,noatime,nodiratime /dev/sda3 /mnt/home
pacstrap /mnt base base-devel linux-lts linux-lts-headers linux-headers memtest86+ grub os-prober efibootmgr efitools btrfs-progs net-tools netctl dialog wpa_supplicant wpa_actiond usb_modeswitch wget smartmontools gdisk fio exfat-utils
genfstab -U -p /mnt >> /mnt/etc/fstab
cp -r ~/efi-2 lxde /mnt/root/
arch-chroot /mnt ~/efi-2
umount -R /mnt
systemctl poweroff