#!/bin/bash
# uprawnienia systemu i uzytkownicy
passwd -l root
# groupadd autologin
groupadd vboxusers
groupadd lpadmin
groupadd sudo
sed -i '/%wheel/a %wheel ALL=(ALL) ALL' /etc/sudoers
sed -i '/%sudo/a %sudo ALL=(ALL) ALL' /etc/sudoers
useradd -m -g users -G audio,disk,network,optical,power,storage,video,rfkill,sudo,lp,lpadmin,scanner,vboxusers,uucp,wheel -s /bin/bash hp
passwd -d hp
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=arch --recheck
grub-install --force /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg
mkdir -p /boot/efi/EFI/Microsoft/Boot
mkdir -p /boot/efi/EFI/Boot
# cp /boot/efi/EFI/arch/grubx64.efi /boot/efi/EFI/Microsoft/Boot/bootmgfw.efi
cp /boot/efi/EFI/arch/grubx64.efi /boot/efi/EFI/Boot/bootx64.efi

# Koliduje z wifi-menu i netctl
# W przypadku modemu hilink i lan odhaczyc # przy systemctl enable dhcpcd
# systemctl enable dhcpcd

chmod -R 777 ~/*
cp -r ~/lxde /home/hp/