#!/bin/bash

umount -l /mnt
mkfs.ext4 /dev/sda1
mkfs.ext4 /dev/sda2
mount /dev/sda1 /mnt
mkdir -p /mnt/home
mount /dev/sda2 /mnt/home
pacstrap /mnt base base-devel linux-lts linux-lts-headers linux-headers memtest86+ grub os-prober btrfs-progs net-tools netctl dialog wpa_supplicant wpa_actiond usb_modeswitch wget smartmontools
genfstab -U -p /mnt >> /mnt/etc/fstab
cp -r /root/bios-2 lxde /mnt/root/
arch-chroot /mnt ./root/bios-2
umount -R /mnt
systemctl poweroff