#!/bin/bash
# uprawnienia systemu i uzytkownicy
passwd -l root
# groupadd autologin
groupadd vboxusers
groupadd lpadmin
groupadd sudo
sed -i '/%wheel/a %wheel ALL=(ALL) ALL' /etc/sudoers
sed -i '/%sudo/a %sudo ALL=(ALL) ALL' /etc/sudoers
useradd -m -g users -G audio,disk,network,optical,power,storage,video,rfkill,sudo,lp,lpadmin,scanner,vboxusers,uucp,wheel -s /bin/bash adamo
passwd -d adamo
grub-install --recheck /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg

# Koliduje z wifi-menu i netctl
# W przypadku modemu hilink i lan odhaczyc # przy systemctl enable dhcpcd
# systemctl enable dhcpcd

chmod -R 777 ~/*
cp -r ~/lxde /home/adamo/