#!/bin/bash
# sudo pacman -S --noconfirm arch-install-scripts archiso
mkdir -p archlive
cp -r /usr/share/archiso/configs/releng/* archlive
cp -r adamo bios-2 lxde ./archlive/airootfs/root
chmod 777 ./archlive/airootfs/root/*
cd archlive
# sed -i '/truncate/s/64M/128M/' build.sh
sed -i '$a [multilib]' pacman.conf
sed -i '$a Include = /etc/pacman.d/mirrorlist' pacman.conf
sed -i '$a [dawidsoft]' pacman.conf
sed -i '$a SigLevel = Never' pacman.conf
sed -i '$a Server = https://github.com/dawidsoft/linux/raw/master/arch-linux/package/$arch' pacman.conf
echo "xorg xf86-video-intel xf86-input-evdev xf86-input-synaptics ttf-dejavu ttf-liberation
lxde gnome-keyring network-manager-applet networkmanager networkmanager-openvpn modemmanager leafpad blueman arc-gtk-theme gnome-themes-standard
gvfs gvfs-nfs gvfs-mtp gvfs-afc gvfs-gphoto2 gvfs-smb gvfs-google cups xscreensaver gnome-screenshot oxygen-icons openvpn openssh nmap
lxshortcut galculator obconf xfce4-notifyd gnome-disk-utility hardinfo git subversion sshfs obexfs hdparm 
xfce4-power-manager firefox-i18n-pl vlc kodi qt4 audacious ghex evince samba brasero youtube-dl pingus pinta
pulseaudio pulseaudio-alsa pavucontrol catfish gthumb wammu libreoffice-fresh-pl sopcast gksu rfkill inxi
zip unzip unrar ntfsprogs p7zip chromium gparted file-roller simple-scan system-config-printer libusb-compat
flashplugin gtk-engines gtk-engine-murrine cpio zenity bash-completion gnome-system-monitor screenfetch mc
xdg-user-dirs xdg-user-dirs-gtk gucharmap ffmpegthumbnailer tumbler libgsf raw-thumbnailer pulseaudio-bluetooth
virtualbox virtualbox-ext-oracle virtualbox-guest-iso virtualbox-host-dkms vinagre x11vnc pepper-flash
arch-install-scripts archiso
wine-staging wine_gecko wine-mono winetricks
lib32-mesa lib32-alsa-lib lib32-libpulse lib32-openal
lib32-libxml2 lib32-mpg123 lib32-lcms2 lib32-giflib lib32-libpng lib32-gnutls
subversion asciidoc bash bc binutils bzip2 fastjar flex git gcc util-linux gawk intltool zlib make ncurses
openssl patch perl-extutils-makemaker rsync sdcc unzip wget gettext libxslt boost libusb bin86 sharutils
b43-fwcutter findutils asciidoc mercurial
aic94xx-firmware atari800 downgrade f3 gigolo gnome-exe-thumbnailer gnurobbo gobi-firmware gobi-loader google-chrome yaourt
lxdm-themes pa-applet-git package-query n2n-git haguichi logmein-hamachi sopcast-player ttf-ms-fonts wd719x-firmware skype" > packages.x86_64
rm -rf airootfs/etc/udev
cp -r /etc/systemd/* airootfs/etc/systemd/
cp -r /etc/xdg airootfs/etc
cp -r /etc/X11 airootfs/etc
cp -r /etc/lxdm airootfs/etc
cp -r ~/.config/lxpanel/LXDE/* airootfs/etc/xdg/lxpanel/LXDE/
cp -r ~/.config/lxsession/LXDE/* airootfs/etc/xdg/lxsession/LXDE/
cp -r ~/.config/pcmanfm/LXDE/* airootfs/etc/xdg/pcmanfm/LXDE/
sed -i '/autologin=dgod/a autologin=root' airootfs/etc/lxdm/lxdm.conf
mkdir airootfs/etc/cups
cp -r /etc/cups/cups-files.conf airootfs/etc/cups/cups-files.conf
sudo ./build.sh -v