#!/bin/bash

umount -l /mnt
mkswap /dev/sda1
mkfs.btrfs -f /dev/sda2
mount -o noatime,nodiratime /dev/sda2 /mnt
swapon /dev/sda1
# mkdir -p /mnt/home
# mount -o noatime,nodiratime /dev/sda2 /mnt/home
pacstrap /mnt base base-devel linux-lts linux-lts-headers linux-headers memtest86+ grub os-prober efibootmgr efitools btrfs-progs net-tools netctl dialog wpa_supplicant wpa_actiond usb_modeswitch wget smartmontools gdisk fio
genfstab -U -p /mnt >> /mnt/etc/fstab
cp -r ~/bios-2 lxde /mnt/root/
arch-chroot /mnt ~/bios-2
umount -R /mnt
systemctl poweroff